name: Doxygen to GitHub Pages

on:
  push:
    branches:
      - main  # Set a branch name to trigger deployment

jobs:
  deploy:
    runs-on: ubuntu-22.04
    permissions:
      contents: write
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - uses: actions/checkout@v3

      - name: Run Doxygen Action
        uses: mattnotmitt/doxygen-action@v1.9.5
        with:
            working-directory: 'doc/'

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        # If you're changing the branch from master,
        # also change the `master` in `refs/heads/master`
        # below accordingly.
        if: ${{ github.ref == 'refs/heads/main' }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./doc/html