name: Doxygen to GitHub Pages
on:
  push:
    branches:
      - main  # Set a branch name to trigger deployment
jobs:
  deploy:
    runs-on: ubuntu-22.04
    permissions:
      contents: write
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - name: Delete branch
        uses: dawidd6/action-delete-branch@v3
        with:
          github_token: ${{github.token}}
          branches: gh-pages
        # if the branch exists, delete it
        if: ${{ github.ref == 'refs/heads/gh-pages' }}
      - uses: actions/checkout@v3
        with:
          submodules: true  # Fetch Hugo themes (true OR recursive)
          fetch-depth: 0    # Fetch all history for .GitInfo and .Lastmod
      - name: Run Doxygen Action
        uses: mattnotmitt/doxygen-action@v1.9.5
        with:
            working-directory: 'docs/'

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        # If you're changing the branch from master,
        # also change the `master` in `refs/heads/master`
        # below accordingly.
        if: ${{ github.ref == 'refs/heads/main' }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs